// Code generated by xgen. DO NOT EDIT.

package schema

// Href ...
type Href string

// Type ...
type Type string

// Role ...
type Role string

// Title ...
type Title string

// Show ...
type Show string

// Actuate ...
type Actuate string
